# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.0.0
group=com.nyfaria
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Water Balloon Mod
mod_author=Nyfaria, SirJain
mod_id=waterballoon
license=ARR
credits=
description=Adds Water Balloons to the game.

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Dependencies
forge_config_api_port_version=20.6.0

# Publishing
curseforge_publishing_enabled=true
curseforge_project_id=1037173
modrinth_publishing_enabled=true
modrinth_project_id=2JEAyza5
dry_run=false
